allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  sharp: false
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
