import { z } from "zod";

export const enrollmentSchema = z.object({
  parentFullName: z.string().trim().min(2),
  parentEmail: z.string().trim().email().transform((value) => value.toLowerCase()),
  parentPhone: z.string().trim().min(10),
  relationship: z.string().trim().min(1),
  preferredContact: z.string().trim().min(1),
  cityState: z.string().trim().min(2),
  studentFirstName: z.string().trim().min(2),
  studentLastName: z.string().trim().min(2),
  studentDob: z.coerce.date(),
  studentAge: z.coerce.number().int().min(5).max(99),
  studentGender: z.string().trim().optional(),
  currentGrade: z.string().trim().min(1),
  schoolName: z.string().trim().min(2),
  techExperience: z.string().trim().min(1),
  bootcampTrack: z.string().trim().min(1),
  formatPreference: z.string().trim().min(1),
  cohortId: z.string().trim().optional(),
  cohortDate: z.string().trim().optional(),
  sessionPreference: z.string().trim().min(1),
  hasComputer: z.string().trim().min(1),
  operatingSystem: z.string().trim().min(1),
  hasInternet: z.string().trim().min(1),
  hasEmail: z.string().trim().min(1),
  emergencyName: z.string().trim().min(2),
  emergencyPhone: z.string().trim().min(10),
  emergencyRelation: z.string().trim().min(1),
  accommodations: z.string().trim().optional(),
  medicalConditions: z.string().trim().optional(),
  studentGoal: z.string().trim().min(10),
  parentExpectation: z.string().trim().min(10),
  referralSource: z.string().trim().min(1),
  planSelection: z.string().trim().min(1),
  promoCode: z.string().trim().optional(),
});

export type EnrollmentInput = z.infer<typeof enrollmentSchema>;
